version: '3.8'

services:
  web:
    build: .
    command: /bin/sh -c "flask db upgrade && gunicorn app:app -b 0.0.0.0:8000 --timeout 120"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait until the database is healthy
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/sampledb
    volumes:
      - .:/sample-app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sampledb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
