version: '3.8'
services:
  app:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/tutorial
    ports:
      - "8000:8000"
    networks:
      - tutorial_network

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tutorial
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tutorial_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tutorial"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  tutorial_network:
    driver: bridge

volumes:
  postgres_data:
