version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a1a1a1
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - ci_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:a1a1a1@postgres:5432/DB
      TEST_DATABASE_URL: postgresql://admin:a1a1a1@postgres/test_db
    ports:
      - "8000:8000"
    networks:
      - ci_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DB"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  ci_network:
    driver: bridge

volumes:
  db:
